version: '3'
services:

  # Content server
  frontend:
    image: travelblog-content
    container_name: travelblog-content
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    logging:
      driver: json-file
    networks:
      travelblogback_app-network:
        aliases:
          - content

#Docker Networks
networks:
  travelblogback_app-network:
    external: true
