version: '3'
services:

  # Content server
  content:
    image: travelblog-content
    container_name: travelblog-content
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    logging:
      driver: json-file
    volumes:
      - resources:/var/lib/resources
    networks:
      travelblogback_app-network:
        aliases:
          - content

#Docker Networks
networks:
  travelblogback_app-network:
    external: true

# Volumes
volumes:
  resources:
    driver: local
